// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_DMRegressionFreq2_TMBExports
#include <TMB.hpp>
#include "DMRegressionFreq.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "DMRegressionFreq") {
    return DMRegressionFreq(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
